/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Sanity check + report fixed_main_v6.py reachability + active model.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Return a summary of every known job.
         */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job State
         * @description Return full job state — the polling endpoint.
         */
        get: operations["get_job_state_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Topics
         * @description Return just the extracted topics for a job.
         */
        get: operations["get_topics_jobs__job_id__topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Script
         * @description Accept a HackMD .md file, extract viz topics with Agent A.
         *
         *     Topic extraction is fast (~one LLM call) so we do it inline. The user
         *     sees the topics list immediately when this returns.
         */
        post: operations["upload_script_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/topics/{topic_id}/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Topic Suggestions
         * @description Run Agent B for one extracted topic. Returns 5 viz suggestions.
         *
         *     Cached on the JobState — calling twice for the same topic_id reuses the
         *     first response so the user can flip back and forth in the UI for free.
         */
        post: operations["get_topic_suggestions_jobs__job_id__topics__topic_id__suggestions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/topics/{topic_id}/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build Topic Viz
         * @description Pick a suggestion (or custom notes) and queue a build.
         */
        post: operations["build_topic_viz_jobs__job_id__topics__topic_id__build_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Manifest
         * @description Return the final embed manifest + token usage totals.
         */
        get: operations["get_manifest_jobs__job_id__manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview File
         * @description Serve a screenshot or generated file by absolute path.
         *
         *     Locked down to paths inside VIZ_OUTPUT_DIR — no traversal allowed.
         */
        get: operations["preview_file_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Index
         * @description Serve the built SPA's index.html.
         */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_script_upload_post */
        Body_upload_script_upload_post: {
            /** Track */
            track: string;
            /** File */
            file: string;
        };
        /**
         * BuildRequest
         * @description Request payload from the frontend when the user picks a suggestion.
         */
        BuildRequest: {
            /**
             * Suggestion Id
             * @description Required unless custom_notes alone is being used.
             */
            suggestion_id?: string | null;
            /**
             * Custom Notes
             * @description Optional free-text customisation appended to the chosen suggestion.
             * @default
             */
            custom_notes: string;
            /**
             * Github Module
             * @description (deprecated) ignored.
             * @default
             */
            github_module: string;
            /**
             * Github Class
             * @description (deprecated) ignored.
             * @default
             */
            github_class: string;
        };
        /** BuildTask */
        BuildTask: {
            /** Id */
            id: string;
            /** Topic Id */
            topic_id: string;
            /** Selected Suggestion Id */
            selected_suggestion_id?: string | null;
            /**
             * Custom Notes
             * @default
             */
            custom_notes: string;
            /**
             * Short Topic
             * @default
             */
            short_topic: string;
            /**
             * Final Viz Brief
             * @default
             */
            final_viz_brief: string;
            /**
             * Phase
             * @default queued
             * @enum {string}
             */
            phase: "queued" | "draft" | "validate" | "polish" | "publish" | "done" | "failed";
            /** Progress Log */
            progress_log?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Project Dir
             * @default
             */
            project_dir: string;
            /**
             * Screenshot Path
             * @default
             */
            screenshot_path: string;
            /**
             * Error
             * @default
             */
            error: string;
            /** Token Usage */
            token_usage?: {
                [key: string]: unknown;
            };
            /**
             * Github Status
             * @default not_started
             */
            github_status: string;
            /**
             * Github Repo Url
             * @default
             */
            github_repo_url: string;
            /**
             * Github Clone Url
             * @default
             */
            github_clone_url: string;
            /**
             * Github Repo Name
             * @default
             */
            github_repo_name: string;
            /**
             * Github Commit Sha
             * @default
             */
            github_commit_sha: string;
            /**
             * Github Error
             * @default
             */
            github_error: string;
            /**
             * Embed Url
             * @default
             */
            embed_url: string;
            /**
             * Repo Edit Url
             * @default
             */
            repo_edit_url: string;
            /**
             * Monorepo Name
             * @default
             */
            monorepo_name: string;
        };
        /**
         * EmbedManifestEntry
         * @description Final per-topic record returned to the content creator.
         */
        EmbedManifestEntry: {
            /** Section */
            section: string;
            /** Embed After Sentence */
            embed_after_sentence: string;
            /** Topic */
            topic: string;
            /** Why Visual Helps */
            why_visual_helps: string;
            /** Viz Title */
            viz_title: string;
            /** Viz Brief */
            viz_brief: string;
            /** Project Dir */
            project_dir: string;
            /**
             * Screenshot Path
             * @default
             */
            screenshot_path: string;
            /**
             * Github Repo Url
             * @default
             */
            github_repo_url: string;
            /**
             * Status
             * @default ok
             * @enum {string}
             */
            status: "ok" | "failed" | "skipped";
            /**
             * Embed Url
             * @default
             */
            embed_url: string;
            /**
             * Repo Edit Url
             * @default
             */
            repo_edit_url: string;
        };
        /**
         * ExtractedTopic
         * @description A pedagogically valuable visualization opportunity in the script.
         */
        ExtractedTopic: {
            /**
             * Id
             * @description Stable id assigned by the orchestrator (topic_1, topic_2 ...)
             */
            id: string;
            /**
             * Section
             * @description Markdown section heading the topic appears under
             */
            section: string;
            /**
             * Topic
             * @description Short topic name suitable as a slug
             */
            topic: string;
            /**
             * Embed After Sentence
             * @description Verbatim sentence from the source after which the viz should be embedded. Must appear EXACTLY in the source for the assembler to find it.
             */
            embed_after_sentence: string;
            /**
             * Why Visual Helps
             * @description One-sentence justification of why a viz adds genuine value here.
             */
            why_visual_helps: string;
            /**
             * Audience Difficulty
             * @default beginner
             * @enum {string}
             */
            audience_difficulty: "beginner" | "intermediate" | "advanced";
            /**
             * Surrounding Context
             * @description ~500 chars of context around the embed point, used by the suggestion agent.
             * @default
             */
            surrounding_context: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ok */
            ok: boolean;
            /** Fixed Main Path */
            fixed_main_path: string;
            /** Fixed Main Exists */
            fixed_main_exists: boolean;
            /** Text Model */
            text_model: string;
            /** Output Dir */
            output_dir: string;
        };
        /** JobState */
        JobState: {
            /** Job Id */
            job_id: string;
            /** Script Name */
            script_name: string;
            /**
             * Track
             * @default Academy DSA
             */
            track: string;
            /** @default uploaded */
            status: components["schemas"]["JobStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Topics */
            topics?: components["schemas"]["ExtractedTopic"][];
            /**
             * Suggestions
             * @description topic_id -> list of viz suggestions
             */
            suggestions?: {
                [key: string]: components["schemas"]["VizSuggestion"][];
            };
            /**
             * Builds
             * @description topic_id -> BuildTask (one viz per topic for now)
             */
            builds?: {
                [key: string]: components["schemas"]["BuildTask"];
            };
            /** Manifest */
            manifest?: components["schemas"]["EmbedManifestEntry"][];
            /**
             * Error
             * @default
             */
            error: string;
            /** Logs */
            logs?: string[];
            /** Token Usage */
            token_usage?: {
                [key: string]: unknown;
            };
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "uploaded" | "topics_extracted" | "awaiting_user_picks" | "building" | "done" | "failed";
        /** JobSummary */
        JobSummary: {
            /** Job Id */
            job_id: string;
            /** Script Name */
            script_name: string;
            status: components["schemas"]["JobStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Topic Count */
            topic_count: number;
            /** Build Count */
            build_count: number;
        };
        /** UploadResponse */
        UploadResponse: {
            /** Job Id */
            job_id: string;
            /** Script Name */
            script_name: string;
            /** Char Count */
            char_count: number;
            status: components["schemas"]["JobStatus"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VizSuggestion */
        VizSuggestion: {
            /**
             * Id
             * @description viz_1 ... viz_5
             */
            id: string;
            /** Title */
            title: string;
            /**
             * Approach
             * @description 2-4 sentences describing what would be built and shown.
             */
            approach: string;
            /**
             * Beginner Benefit
             * @description One sentence of value for a beginner learner.
             */
            beginner_benefit: string;
            /**
             * Intermediate Benefit
             * @description One sentence of value for an intermediate learner.
             */
            intermediate_benefit: string;
            /**
             * Complexity
             * @default medium
             * @enum {string}
             */
            complexity: "low" | "medium" | "high";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"][];
                };
            };
        };
    };
    get_job_state_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topics_jobs__job_id__topics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_script_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_script_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topic_suggestions_jobs__job_id__topics__topic_id__suggestions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_topic_viz_jobs__job_id__topics__topic_id__build_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_manifest_jobs__job_id__manifest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_file_preview_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
}
